#name是你的插件名称,这个可以任意
name: QQGroupMessagePlugin
#main是你的包名+类名
main: com.sweetcreeper.qqplugin.Qqplugin
#version 这个是版本号
version: 1.0
#commands:
  # test:
  #   description: Test命令
  #   usage: /test 输出